services:
  drivenops_db:
    image: postgres
    container_name: drivenops_db
    restart: always
    ports:
      - 5432:4321
    env_file:
      - ./back-end/.env
    volumes:
      - drivenops_db:/var/lib/postgresql/data
  node_app:
    container_name: node_app
    build: ./back-end/
    ports:
      - 5000:5000
    depends_on:
      - drivenops_db
    env_file:
      - ./back-end/.env
  react_drivenops_app: 
    container_name: react_drivenops_app
    build: ./front-end
    volumes:
      - build_react:/var/www/html
    stdin_open: true
  nginx_drivenops_app: 
    container_name: nginx_drivenops_app
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - drivenops_db
      - node_app
      - react_drivenops_app
volumes:
  drivenops_db:
  build_react: